/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS FILE IS NORMALLY AUTO-GENERATED BY `npx convex dev`. Hand-written here to
 * match codegen output exactly because this environment runs offline.
 *
 * @module
 */

import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's public API.
 */
export const api = anyApi;

/**
 * A utility for referencing Convex functions in your app's internal API.
 */
export const internal = anyApi;
