/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS FILE IS NORMALLY AUTO-GENERATED BY `npx convex dev`. Hand-written here to
 * match codegen output exactly because this environment runs offline.
 *
 * @module
 */

import type * as auth from "../auth.js";
import type * as comments from "../comments.js";
import type * as crons from "../crons.js";
import type * as http from "../http.js";
import type * as internal_ from "../internal.js";
import type * as orgs from "../orgs.js";
import type * as tickets from "../tickets.js";
import type * as types from "../types.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  comments: typeof comments;
  crons: typeof crons;
  http: typeof http;
  internal: typeof internal_;
  orgs: typeof orgs;
  tickets: typeof tickets;
  types: typeof types;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
